app:
  jwt:
    secret: "eC4mS38xW9aX63zPq9bTzE89nFjwB1LmTzUvW4zMdpQ2vNsP7yWhNfpZJ8E7CtQx"

spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/postgres
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  flyway:
    baseline-on-migrate: false

  jpa:
    hibernate:
      ddl-auto: none  # zůstává, pokud Hibernate nemá dělat nic
    properties:
      # javax.persistence.schema-generation.* už nepotřebujeme, generování přes Hibernate jsme vypnuli
      # javax:
      #   persistence:
      #     schema-generation:
      #       scripts:
      #         action: create
      #         create-target: schema.sql
      #         create-source: metadata
      hibernate:
        format_sql: true  # necháváme pro lepší čitelnost SQL výstupu
    database-platform: org.hibernate.dialect.PostgreSQLDialect  # volitelné, Hibernate si dnes typ DB pozná sám
    show-sql: true  # necháváme pro debugování

  security:
    user:
      name: admin
      password: admin

  sql:
    init:
      mode: never

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

server:
  port: 8080
  servlet:
    context-path: /thirstyPlants/api
    encoding:
      charset: UTF-8
      enabled: true
      force: true
