
create table account (
                         id bigint generated by default as identity,
                         email varchar(255) not null unique,
                         password_hash varchar(255) not null,
                         primary key (id)
);

create table flower (
                        watering_frequency_days integer not null,
                        home_id bigint not null,
                        id bigint generated by default as identity,
                        watter timestamp(6) with time zone not null,
                        cloudflare_image_id varchar(255),
                        name varchar(255) not null,
                        primary key (id)
);

create table home (
                      id bigint generated by default as identity,
                      owner_id bigint not null,
                      name varchar(255) not null,
                      primary key (id)
);

create table home_account (
                              account_id bigint not null,
                              home_id bigint not null,
                              primary key (account_id, home_id)
);

alter table if exists flower
    add constraint FK8kb5nj8y8fv1uw8yj13b8uyxb
        foreign key (home_id)
            references home;

alter table if exists home
    add constraint FKsw0q0wg4iwnlveh3jcq26rtn1
        foreign key (owner_id)
            references account;

alter table if exists home_account
    add constraint FKlphjor4wfdmj33t1ruixnusot
        foreign key (account_id)
            references account;

alter table if exists home_account
    add constraint FK4wjyjeg1uhlejxr8ju5an0stu
        foreign key (home_id)
            references home;
